# Select the base image
FROM maven:3.6-jdk-8

# Copy the project files
COPY ./pom.xml ./pom.xml

# Build all dependencies for offline use
RUN mvn dependency:go-offline -B

# Copy your other files
COPY ./src ./src

# Build for release
RUN mvn package

# Set the startup command to run your binary
CMD ["java", "-jar", "./target/my-project.jar"]